# Generated by Django 3.0.4 on 2020-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20200330_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loan_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
