# Generated by Django 3.0.4 on 2020-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_book_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='loan_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
